orchestration/README.md
Document how to work around CSRF token errors in Temporal UI by setting a configuration value at deploy time. Long term this will be solved by proper TLS configuration, and I the linked JIRA ticket is about that, but the workaround will suffice for now.
Manually deployed Temporal helm chart using the documented option, verified that it resolves CSRF token errors.
=> SCOUT-21 Document setting TEMPORAL_CSRF_COOKIE_INSECURE=true in Temporal helm deploy

helm/orchestration/temporal-java.values.yaml, orchestration/temporal-java/src/main/java/edu/washu/tag/temporal/workflow/IngestHl7LogWorkflowImpl.java
Update Temporal workflow `IngestHl7LogWorkflow` input handling so that if no `"date"` input arg is passed, we run the workflow with yesterday's date. This will let us schedule daily workflow runs to ingest the newest HL7 log file.
No user-facing changes
This changes how the `"date"` input arg is handled in the `IngestHl7LogWorkflow` Temporal workflow.
- If a date is passed, we use it. This is the previous behavior.
- If a date is not passed we use the Temporal SDK to read a workflow [search attribute](https://docs.temporal.io/workflows#action) `TemporalScheduledStartTime`.
- If this attribute is empty, then the `date` is left as `null`. (Side note: I also added handling for any of the input values being `null` or empty, which we treat as a non-retryable error for this workflow run.)
- If …
=> SCOUT-23 Hl7LogExtractor orchestration can ingest "yesterday"'s logs on a scheduled run

.github/workflows/ci.yaml
N/A
Andy had a PR recently that couldn't merge, presumably because the branch protection was seeing the workflow was out of date. With some extra triggers, we can hopefully pre-emptively launch the workflow again to avoid that.
N/A
N/A
N/A
N/A
N/A
N/A
N/A
=> Run ci workflow when PR edited/synchronize

.github/workflows/ci.yaml
If this pull request is for work that is behind a feature flag, or for documentation or test updates, most of the details below are not required; The level of attention to each is left to the discretion of the developer. 
For all other change types, the developer should attempt to provide as much detail as is reasonable.
N/A
Linting and building the images do not actually depend on each other, so we can speed up the action by allowing them to run in parallel.
N/A
N/A
N/A
N/A
N/A
N/A
N/A
=> Allow lint and image builds in parallel

.github/workflows/ci.yaml, orchestration/temporal-java/src/test/resources/application.yaml
This adds an `application.yaml` in the temporal-java test resources to use temporal's test server. Additionally, I added it as a job in github actions so we can have it running automatically.
The new `unit-test` job runs in parallel with linting and the build+upload job. All 3 are required to pass before integration tests launch.
N/A
N/A
N/A
N/A
N/A
It works on my machine. Making this PR should trigger a test run on github actions as another 👍 
N/A
=> SCOUT-44 Enabling unit tests in GHA

orchestration/temporal-java/build.gradle, orchestration/temporal-java/src/main/java/edu/washu/tag/temporal/activity/SplitHl7LogActivityImpl.java, orchestration/temporal-java/src/main/java/edu/washu/tag/temporal/model/FindHl7LogFileOutput.java, orchestration/temporal-java/src/main/java/edu/washu/tag/temporal/model/SplitHl7LogActivityInput.java, orchestration/temporal-java/src/main/java/edu/washu/tag/temporal/model/SplitHl7LogActivityOutput.java, orchestration/temporal-java/src/main/java/edu/washu/tag/temporal/model/TransformSplitHl7LogInput.java, orchestration/temporal-java/src/main/java/edu/washu/tag/temporal/model/TransformSplitHl7LogOutput.java, orchestration/temporal-java/src/main/java/edu/washu/tag/temporal/workflow/IngestHl7LogWorkflowImpl.java
The HL7 log ingest workflow can now accept multiple dates for its input. These are specified using the same `"date"` input parameter, the value of which can now be interpreted as a comma-separated string of dates. So `"20000101"` is valid, as is `"2000-01-01"`, as is `"20000101,20221231,1994-03-15"`, etc.
The workflow has been refactored with the idea that its input will be a list of dates. All the subsequent steps and actions are looped over the input dates.
At the final step, which is sent from the java workflow/actions over to the python action, the files to ingest are aggregated into groups by year. This is to minimize the potential for multiple concurrent processes attempting to write to the same files, which are partitioned by year.
N/A
N/A
N/A
This does and will have performance …
=> SCOUT-52 Add bulk HL7 log extraction + improve race conditions

orchestration/temporal-java/build.gradle, orchestration/temporal-java/scripts/transform-split-hl7-log.sh, orchestration/temporal-java/src/main/java/edu/washu/tag/temporal/config/S3Config.java, orchestration/temporal-java/src/main/java/edu/washu/tag/temporal/workflow/IngestHl7LogWorkflowImpl.java
Ingest HL7 Logs workflow should be more stable with fewer activity timeouts and better error catching.
- Detect "bad files" which aren't proper HL7 logs after splitting and produce an informative error
- In fan-out steps, let individual activities fail without failing the whole workflow. Unless they all failed, then do fail the workflow.
- Tweak activity timeouts and retries
- Increase size of connection pool in Apache HTTP client underlying S3 client
N/A
N/A
The performance should either be the same or better. I expect fewer failures which lead to fewer retries which means higher overall throughput.
Better handling for bad data flies that are not actually hl7 logs.
N/A
Manually tested with large numbers of dates, with and without a single bad file.
N/A
=> Improve HL7 workflow stability

helm/jupyter/hub/hub-values.yaml
- Jupyter single user notebooks need explicit egress configuration to Minio. We had changed the Minio namespace and port without updating this egress. 
- Can't access data without egress to Minio
- N/A
- Still having other Spark notebook issues, but pretty sure we need this.
- [] I have added unit tests, unless this is a test code PR.
=> Update Jupyter single user notebook egress to minio

.github/actions/docker-build-cache/action.yaml
N/A
Cache docker build artifacts in GitHub CI. This should reduce image build times when setup steps aren't changed.
See https://docs.docker.com/build/cache/backends/gha/
N/A
N/A
N/A
N/A
N/A
None yet. Need to open this PR for the action to run.
I'm not 100% certain but fairly confident that we can manage the cached artifacts manually in the GH UI or CLI if for whatever reason we need to purge the cache and build fresh.
=> Cache docker build artifacts to reduce build times

orchestration/temporal-java/src/main/java/edu/washu/tag/temporal/util/Hl7LogSplitter.java, orchestration/temporal-java/src/main/java/edu/washu/tag/temporal/util/Hl7LogTransformer.java
N/A
I tested the workflow on the identified sample data. It failed to split files with non-ASCII characters.
```
{
"message": "Activity task failed",
"cause": {
"message": "Failed to split log file /data/<some file>.log",
"source": "JavaSDK",
"stackTrace": "io.temporal.failure.ApplicationFailure.newFailureWithCause(ApplicationFailure.java:95)
edu.washu.tag.temporal.activity.SplitHl7LogActivityImpl.splitHl7Log(SplitHl7LogActivityImpl.java:68)
java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
java.base/java.lang.reflect.Method.invoke(Method.java:580)
io.temporal.internal.activity.RootActivityInboundCallsInterceptor$POJOActivityInboundCallsInterceptor.executeActivity(RootActivityInboundCallsInterceptor.java:64) …
```
=> SCOUT-62 Read log file with encoding ISO-8859-1 when splitting, not transforming

orchestration/temporal-java/src/main/java/edu/washu/tag/temporal/activity/FindHl7LogsActivity.java, orchestration/temporal-java/src/main/java/edu/washu/tag/temporal/activity/FindHl7LogsActivityImpl.java, orchestration/temporal-java/src/main/java/edu/washu/tag/temporal/model/ContinueIngestWorkflow.java, orchestration/temporal-java/src/main/java/edu/washu/tag/temporal/model/FindHl7LogFileInput.java, orchestration/temporal-java/src/main/java/edu/washu/tag/temporal/model/FindHl7LogFileOutput.java, orchestration/temporal-java/src/main/java/edu/washu/tag/temporal/model/IngestHl7LogWorkflowInput.java, orchestration/temporal-java/src/main/java/edu/washu/tag/temporal/util/AllOfPromiseOnlySuccesses.java, orchestration/temporal-java/src/main/java/edu/washu/tag/temporal/util/Constants.java, orchestration/temporal-java/src/main/java/edu/washu/tag/temporal/util/FileHandler.java, orchestration/temporal-java/src/main/java/edu/washu/tag/temporal/util/FileHandlerImpl.java, orchestration/temporal-java/src/main/java/edu/washu/tag/temporal/workflow/IngestHl7LogWorkflowImpl.java, orchestration/temporal-java/src/main/resources/application.yaml, orchestration/temporal-java/src/test/resources/application.yaml
Large ingest workflows will be split into smaller batches.
The ingest workflow will ingest only a certain (configurable) number of log files before starting a new workflow using the Continue-As-New mechanism which will continue processing the rest.
N/A
N/A
The intent of this change is to enable the temporal ingest workflow to run larger ingests without running into temporal limits. Performance should be similar to before, except that what would have been a single large workflow before will be batched into smaller workflows.
N/A
N/A
I set an artificially low limit on the number of child workflows (50) and ran the test dataset. Verified that it correctly chunks the log files and continues a new workflow.
I ran other data sets as well, and they seemed to also work fine, but they took much …
=> SCOUT-61 Continue as new

helm/grafana/alerts/alert-rules/high-node-cpu-iowait-usage-alert.json, helm/grafana/alerts/alert-rules/high-node-cpu-usage-alert.json, helm/grafana/alerts/alert-rules/high-node-disk-usage-alert.json, helm/grafana/alerts/alert-rules/high-node-memory-usage-alert.json, helm/grafana/alerts/alert-rules/high-node-system-load-alert.json
- Reconfigure Grafana alerts to keep their last state (Normal/Error) in the event of no data, execution errors, or timeouts. 
- The prometheus kube state metrics exporter restarts occasionally resulting in data source errors being thrown which aren't helpful and make the slack channel too noisy.
N/A
N/A
N/A
N/A
N/A
Tested by restarting the kube state metrics deployment on big-02 and did not see errors in grafana or slack.
=> Reconfigure no data and error options handling for Grafana alert instances

helm/grafana/alerts/alert-rules/high-node-mount-inode-usage-alert.json, helm/grafana/kustomization.yaml
-  Introduces a new alert for monitoring high inode usage on node mount points. Users will be notified when inode usage exceeds 90% on a mount (/, /scout/data, /scout/persistence, ...).
N/A
N/A
N/A
- Removed ceph filesystem type from promql query, we are not storing data there and inodes free is not appearing correctly. Even `df -i` does not show IFree for the /ceph/tag/home mount
- Yes
Reviewed the alert on big-02.
N/A
=> Add alert for high inode usage

orchestration/temporal-python/src/temporalpy/ingesthl7worker.py
Based on these [Temporal Worker Performance Options](https://docs.temporal.io/develop/worker-performance#invariants), limit the workflow cache size and number of concurrent python worker workflows to 1 to align with the number of threads provided to the worker and the number of concurrent activities. We also are running workflows with large amounts of memory for Spark and need to limit caching that.
Overall performance should be similar, I didn't notice any changes during testing.
N/A
N/A
Tested against our large test datasets. In Grafana, memory usage for the python worker resets in between ingests to the deltalake as expected.
=> Limit cached and concurrent python worker workflows

ansible/playbooks/jupyter.yaml, helm/jupyter/hub/hub-values.yaml
- Fix issue with single-user notebook storage.
When [updating storage classes and PVs](https://github.com/washu-tag/scout/pull/50), the single-user pods are unable to bind to the pv/pvc shared with the Hub. But single-user pods probably shouldn't share a pv/pvcC with the Hub. This gives the hub one pv/pvc and all single-user pods share a pv/pvc.
Fixes issue introduced in https://github.com/washu-tag/scout/pull/50. The behavior is the same from a user perspective, but instead of each single-user pod getting it's own pv/pvc, all single-user pods share a pv/pvc. I tried to setup a rancher/local-path-provisioner specifically for Jupyter pods but was not able to do so quickly. This unblocks Jupyter and is okay for now
Tested on big-02. I was able to log out/in and my notebooks were persisted.
=> Fix Single-User Jupyter Notebook Pod PV/PVC Binding Issue

helm/orchestration/temporal-python.values.yaml, helm/orchestration/temporal-worker/templates/deployment.yaml, helm/orchestration/temporal-worker/values.yaml, orchestration/temporal-python/pyproject.toml, orchestration/temporal-python/src/temporalpy/activities/ingesthl7.py, orchestration/temporal-python/src/temporalpy/healthapi.py, orchestration/temporal-python/src/temporalpy/hl7extractor/deltalake.py, orchestration/temporal-python/src/temporalpy/ingesthl7worker.py
This adds a health check to the python worker, so that if spark dies or whatever we can signal to kubernetes that it needs to restart the pod.
There are two main pieces
1. Add a small FastAPI server with a `/healthz` API endpoint. When the API is hit it checks the contents of a temp file; if there is anything in the file it reports that the pod is unhealthy. We configure the helm chart so kubernetes will periodically check this API for health.
2. In the main worker code, if certain spark-y exceptions are caught, write the error message to the health check temp file.
N/A
I don't think there are any security implications here.
- I did initially hard-code the path to the temp health check file, but I thought that might open some kind of attack (though I'm not sure how it would actually …
=> Add python worker health check for spark

.github/actions/docker-build-cache/action.yaml, .github/workflows/ci.yaml
N/A
This change breaks up building and uploading the docker images as artifacts from 1 job to `n`. _Technically_, it is a bit less efficient in terms of compute resources because each job will need to call the checkout/setup steps, but the benefit (which I'm pretty confident outweighs the cost until/if we start needing to be more judicious with github runners) is that the docker builds can all run in parallel, which significantly cuts down on the total time of the CI workflow.
N/A
N/A
N/A
N/A
N/A
CI workflow still passing after changes.
N/A
=> Parallel docker builds

orchestration/temporal-python/src/temporalpy/healthapi.py
If this pull request is for work that is behind a feature flag, or for documentation or test updates, most of the details below are not required; The level of attention to each is left to the discretion of the developer. 
For all other change types, the developer should attempt to provide as much detail as is reasonable.
Python worker health API 500 error due to exception in health check method itself returns generic error message instead of stack trace.
Log stack trace rather than passing it through to user
N/A
Should improve security posture by not sharing stack trace info with end user.
N/A
N/A
N/A
No testing, this is a blind code change.
=> Remove stack trace from REST API response

ansible/inventory.example.yaml, ansible/playbooks/jupyter.yaml, ansible/playbooks/vars/jupyter.auth.dummy.values.yaml, ansible/playbooks/vars/jupyter.auth.github.values.yaml, ansible/playbooks/vars/jupyter.values.yaml
- JupyterHub can now be deployed with dummy authentication in addition to GitHub authentication
- Adds ability to restrict access to JupyterHub by username
Less secure than GitHub but is needed as a stopgap until we can configure DNS and WashU Key.
N/A
N/A
The username JupyterHub uses for storing user notebooks is not associated with the authentication source. As long as we use our WashU keys for dummy auth we will be able to easily migrate.
Tested dummy and GH auth. Also tested migrating from dummy to GH auth using my GH username.
N/A
=> JupyterHub Dummy Auth

ansible/playbooks/vars/jupyter.values.yaml
- Fixes login failure issue in air-gapped environments where external network access is restricted
- JupyterHub was attempting to verify latest notebook image availability during user login, failing when internet access was unavailable
- Updated the notebook image pull policy to "Never" to prevent runtime image verification attempts at user login
- Explicitly configured image pulling to occur only during helm upgrade/install. This documents the expected behavior in our configuration files rather than relying on JupyterHub defaults
N/A
N/A
N/A
N/A
N/A
- Tested on tagdev-big-02 by simulating air-gapped environment using iptables rules to block external network traffic
- Verified successful login and notebook startup under restricted network conditions
- Confirmed image pull behavior during …
=> Update JupyterHub Notebook Image Pull Policies

.github/ci_resources/inventory.yaml, .github/workflows/ci.yaml, ansible/inventory.example.yaml, ansible/playbooks/extractor.yaml, ansible/playbooks/orchestrator.yaml, ansible/playbooks/postgres.yaml, ansible/playbooks/services/grafana.yaml, ansible/playbooks/services/minio.yaml, ansible/playbooks/services/superset.yaml, ansible/playbooks/services/trino.yaml, ansible/playbooks/tasks/spark_config_setup.yaml, ansible/playbooks/vars/hive.values.yaml, ansible/playbooks/vars/minio.yaml
I believe the only product-facing change for this PR is that the minio credentials exposed via Jupyter (via Spark config) are now restricted to RO access to `lake` bucket.
* Postgres: create different users for the 3 different databases. Users are still database owners, read-only permissions are enforced through use of the `postgres-cluster-r` service.
* Minio: create different users and buckets, with access policies specifying the actions each can take.
* `lake-reader`: read access for `lake` bucket, used for Jupyter (via Spark config)
* `lake-writer`: write access for `lake` and `scratch` buckets, used for Extractors (directly and via Spark for HL7 ingest), Hive, and Trino (Trino needs write access to allow Superset to create tables, which is needed if users want to inner join the delta …
=> Set up separate users and permissions for postgres databases and minio buckets

extractor/hl7log-extractor/src/main/java/edu/washu/tag/extractor/hl7log/activity/FindHl7Files.java, extractor/hl7log-extractor/src/main/java/edu/washu/tag/extractor/hl7log/activity/FindHl7FilesImpl.java, extractor/hl7log-extractor/src/main/java/edu/washu/tag/extractor/hl7log/activity/SplitHl7LogActivityImpl.java, extractor/hl7log-extractor/src/main/java/edu/washu/tag/extractor/hl7log/db/Hl7File.java, extractor/hl7log-extractor/src/main/java/edu/washu/tag/extractor/hl7log/db/Hl7FileLogFileSegmentNumber.java, extractor/hl7log-extractor/src/main/java/edu/washu/tag/extractor/hl7log/db/IngestDbService.java, extractor/hl7log-extractor/src/main/java/edu/washu/tag/extractor/hl7log/db/IngestDbServiceImpl.java, extractor/hl7log-extractor/src/main/java/edu/washu/tag/extractor/hl7log/model/WriteHl7FilesErrorStatusToDbInput.java, extractor/hl7log-extractor/src/main/java/edu/washu/tag/extractor/hl7log/model/WriteHl7FilesErrorStatusToDbOutput.java, extractor/hl7log-extractor/src/main/java/edu/washu/tag/extractor/hl7log/workflow/IngestHl7ToDeltaLakeWorkflowImpl.java
If python activity fails even after all its retries, we assume that none of the HL7 files that it was supposed to ingest into delta lake made it successfully and write an error status into the database for all of them.
- Switch the python activity invocation from sync to async
- If it failed, catch the exception and execute a new activity
- In this activity we read the manifest file to get all the HL7 files that were supposed to be ingested. We do a query to find their log files and segment numbers, and write error statuses for all of them.
This shouldn't be a problem. The size of the manifest file is constrained by the same setting that constrains the size of the spark jobs, so I don't think we need to worry about any of our db operations getting too big.
I don't like having to do a …
=> Handle python/spark activity failure

tests/src/test/java/edu/washu/tag/BaseTest.java, tests/src/test/java/edu/washu/tag/tests/TestStatusDatabase.java
N/A
Improves the method that launches the ingest in tests to:
1. Log more as it goes along.
2. Fail immediately if the workflow hits "FAILED" rather than waiting for the full polling duration.
N/A
N/A
N/A
N/A
N/A
Tested on VM, and should run here on PR.
=> Improved logging and failure behavior in tests

helm/grafana/dashboards/hl7-ingest-dashboard.json
- Updated the HL7 Ingest Grafana Dashboard to use base 2 logarithmic scaling for axes.
- This change improves readability, especially when there are large disparities in values.
N/A
N/A
N/A
N/A
This change does not affect backward compatibility.
See screenshots for testing of base 2 and base 10 scaling. Base 2 was more readable. It was not possible to adjust the tick density for base 10.
N/A
=> Improve HL7 Ingest Dashboard Readability with Base 2 Log Scaling

.github/workflows/ci.yaml, extractor/hl7log-extractor/src/main/java/edu/washu/tag/extractor/hl7log/activity/SplitHl7LogActivityImpl.java, tests/src/test/java/edu/washu/tag/tests/TestStatusDatabase.java, tests/staging_test_data/hl7/1999/19991130.log
If a logfile doesn't contain any HL7, we write an error message to the hl7 table for segment 0 saying "Log did not contain any HL7 messages". I debated if this should be an error on the log file itself, but I felt like the hl7 table gets a little more visibility and was consistent with prior behavior (which would have produced the message "Split content has fewer than 3 lines").
The HL7 logs may contain multiple lines from the HL7 receiver about the TCP connection, interspersed between HL7 segments. 
This extractor used to assume that after a blank line or at the start of the log file, we would see precisely one timestamp line, one `<SB>` tag, and then everything up through the next blank line was treated as HL7 content.
This change assumes that an HL7 message is demarcated by an `<SB>` …
=> Handle unanticipated TCP chatter in HL7 logs

ansible/inventory.example.yaml, ansible/playbooks/templates/grafana/alerts/no-hl7-from-scheduled-ingest-alert.json.j2, ansible/playbooks/templates/grafana/notification-policy.yaml.j2, ansible/playbooks/templates/hl7log-extractor.values.yaml.j2, ansible/playbooks/vars/minio.yaml, docs/source/ingest.md, extractor/hl7log-extractor/src/main/java/edu/washu/tag/extractor/hl7log/model/IngestHl7FilesToDeltaLakeInput.java, extractor/hl7log-extractor/src/main/java/edu/washu/tag/extractor/hl7log/model/IngestHl7LogWorkflowInput.java, extractor/hl7log-extractor/src/main/java/edu/washu/tag/extractor/hl7log/util/DefaultArgs.java, extractor/hl7log-extractor/src/main/java/edu/washu/tag/extractor/hl7log/workflow/IngestHl7LogWorkflowImpl.java, extractor/hl7log-extractor/src/main/java/edu/washu/tag/extractor/hl7log/workflow/IngestHl7ToDeltaLakeWorkflowImpl.java, extractor/hl7log-extractor/src/main/resources/application.yaml, extractor/hl7log-extractor/src/test/java/edu/washu/tag/extractor/hl7log/IngestHl7LogWorkflowInputParserTest.java, extractor/hl7log-extractor/src/test/resources/application.yaml
User can specify delta ingest timeout via Ansible or at runtime (via workflow parameters). Delta ingest retries reduced from 10 to 5, and wait period increased from 1s to 5min.
Also, a quick bugfix for "no HL7" alert - dropping repeat to 999w (essentially: do not repeat).
Also, turn down [minio scanning](https://min.io/docs/minio/linux/operations/concepts/scanner.html)
(See #106 for similar change on the split & upload side of things.)
N/A
N/A
N/A
N/A
Yes, it's backward compatible.
CI and `big-04`
N/A
=> Make delta ingest timeout configurable and small fixes to "no HL7" alert

ansible/inventory.example.yaml, ansible/playbooks/templates/hl7log-extractor.values.yaml.j2, docs/source/ingest.md, extractor/hl7log-extractor/src/main/java/edu/washu/tag/extractor/hl7log/activity/SplitHl7LogActivityImpl.java, extractor/hl7log-extractor/src/main/java/edu/washu/tag/extractor/hl7log/model/IngestHl7LogWorkflowInput.java, extractor/hl7log-extractor/src/main/java/edu/washu/tag/extractor/hl7log/model/IngestHl7LogWorkflowParsedInput.java, extractor/hl7log-extractor/src/main/java/edu/washu/tag/extractor/hl7log/util/DefaultArgs.java, extractor/hl7log-extractor/src/main/java/edu/washu/tag/extractor/hl7log/util/IngestHl7LogWorkflowInputParser.java, extractor/hl7log-extractor/src/main/java/edu/washu/tag/extractor/hl7log/workflow/IngestHl7LogWorkflowImpl.java, extractor/hl7log-extractor/src/main/resources/application.yaml, extractor/hl7log-extractor/src/test/java/edu/washu/tag/extractor/hl7log/IngestHl7LogWorkflowInputParserTest.java, extractor/hl7log-extractor/src/test/resources/application.yaml
When a temporal user cancels the `IngestHl7LogWorkflow`, the running split & upload activities now get cancelled, and this is reflected in the UI (first cancelation is requested, once the activities stop, it's marked as cancelled).
This also adds a heartbeat timeout, which I've defaulted to 30m but made adjustable via Ansible and as part of the input. The idea here is to have a more fine-grained read on whether an activity is still working (versus having to wait the whole `startToClose` timeout). As such, I've bumped up the default `startToClose` timeout for the split & upload activity to 8hrs, though this can still be adjusted via Ansible and as an input parameter.
Added heartbeat calls. Cancellation causes the heartbeat method to throw an exception, which culminates in the activities …
=> Add heartbeats to split and upload activity for fine-grained timeout and proper cancellation

extractor/hl7-transformer/src/hl7scout/db.py, extractor/hl7-transformer/src/hl7scout/hl7extractor/deltalake.py, tests/src/test/java/edu/washu/tag/tests/TestStatusDatabase.java
Write a `"success"` message to the ingest database for HL7 files which get fully ingested into delta lake.
N/A
This will make the python spark ingest activity take a bit longer. I don't know exactly how much longer. But there is some increased risk of the activity hitting the timeout and getting canceled.
N/A
N/A
Updated the integration tests to check the new `"success"` status.
I haven't updated the grafana ingest dashboard to account for this new information.
=> Write "success" status at the end of ingest

.github/workflows/ci.yaml, extractor/hl7log-extractor/src/main/java/edu/washu/tag/extractor/hl7log/activity/FindHl7LogsActivityImpl.java, extractor/hl7log-extractor/src/test/java/edu/washu/tag/extractor/hl7log/FindLogFileTest.java
If this pull request is for work that is behind a feature flag, or for documentation or test updates, most of the details below are not required; The level of attention to each is left to the discretion of the developer. 
For all other change types, the developer should attempt to provide as much detail as is reasonable.
N/A
Catch exceptions that can happen during directory walk due to an ongoing sync operation making temporary lockfiles (or other such issues).
N/A
N/A
I don't think this will have a significant performance impact, but I didn't dig in to the internals of walk vs walkFileTree.
N/A
No issues
Running CI
I added a couple unit tests for this part of the code. I wanted to try some TDD, but I couldn't easily recreate the exception we were seeing (was starting to get into needing …
=> Use walkFileTree to handle errors during directory walk

ansible/playbooks/templates/grafana/grafana.values.yaml.j2
Set the HL7 Ingest dashboard as the Grafana homepage default.
N/A
N/A
N/A
N/A
Yes, it is backward compatible.
Tested on big-02. The HL7 Ingest dashboard is now the home screen default.
N/A
=> Set Grafana Default Home Dashboard

ansible/playbooks/files/grafana/dashboards/hl7-ingest-dashboard.json
In the HL7 Ingest Grafana dashboard, show different non-failed ingest statuses—namely "success" and "staged"—as different colors in a stacked bar chart.
- Added `status` column to ingest dashboard query
- Added post-query transformation to pivot the status values to columns
- Changed the color scheme to show the status column values in different colors
Also, I reverted the dashboard query back to an earlier form that first generates a date series for all days in the user-selected range then joins that to the data of interest. With the current query I was not seeing any gaps in the chart for missing days, I was only seeing bars for the days that had data that expanded to fill the whole width.
N/A
The postgres queries we're running to generate the charts may have a high cost. I plan to …
=> Distinguish "success" and "staged" in ingest dashboard

extractor/hl7-transformer/src/hl7scout/db.py, extractor/hl7log-extractor/src/main/java/edu/washu/tag/extractor/hl7log/db/IngestDbServiceImpl.java
No product-facing changes
Swap from batch insert to COPY. See [this article](https://www.timescale.com/learn/testing-postgres-ingest-insert-vs-batch-insert-vs-copy) for more information and benchmarks. Also, from [psycopg3 docs](https://www.psycopg.org/psycopg3/docs/api/cursors.html#psycopg.Cursor.executemany):
>This is more efficient than performing separate queries, but in case of several INSERT (and with some SQL creativity for massive UPDATE too) you may consider using [copy()](https://www.psycopg.org/psycopg3/docs/api/cursors.html#psycopg.Cursor.copy).
N/A
N/A
This change takes the "success status" insert from python worker from 90min down to 10min (prior to postgres optimizations).
N/A
Yes
Run the 15M reports on `big-04`
This is much less necessary than before the postgres …
=> Optimize db write from python worker

extractor/hl7-transformer/src/hl7scout/hl7extractor/deltalake.py, tests/src/test/resources/spark_queries.json
Timestamp columns (`message_dt`, `requested_dt`, `observation_dt`, `observation_end_dt`, and `results_report_status_change_dt`) are no longer null when their source HL7 data is non-null.
Added test to verify `message_dt` is not null for any ingested test data.
When parsing timestamp columns, correctly reference column using spark `col(...)` function instead of just column name string.
Ran the CI test suite on big-03. Manually queried table data in jupyter notebook; verified timestamps aren't all null.
N/A
=> Fix null timestamps

extractor/hl7-transformer/pyproject.toml, extractor/hl7-transformer/src/hl7scout/ingesthl7worker.py
No change
* Update temporal worker settings for HL7 transformer per SDK release 1.12. 
>ValueError: Invalid worker config: `max_cached_workflows` > 0 requires `workflow_task_poller_behavior` to be at least 2
* Pin python SDK version, allowing only patch changes for future.
N/A
N/A
I am assuming this will not negatively impact performance, as we're now abiding Temporal's recommendation.
N/A
All good.
None yet, will test via CI and then over the weekend with bolus of other changes.
=> Fix required for Temporal Python SDK v1.12.0, pin version for future

.github/workflows/ci.yaml, tests/src/test/java/edu/washu/tag/BaseTest.java, tests/src/test/java/edu/washu/tag/tests/TestScoutQueries.java, tests/src/test/java/edu/washu/tag/tests/TestStatusDatabase.java, tests/src/test/resources/spark_queries.json
N/A
1. Modifies the ci configuration so that branches starting with `ci-` will have CI launched on them automatically on pushes.
2. Adds Flavin's test for no null message dt elements in a simpler form.
3. Adds a new test to check many more of the columns in the delta lake.
4. Adds a new test to repeat a full ingest request to make sure the delta lake does not get duplicate rows.
N/A
N/A
N/A
N/A
N/A
Tests fully passing on CI.
=> Test additions & CI tweak

ansible/playbooks/vars/jupyter.values.yaml
- Increase JupyterHub Spawner http_timeout to 120s. Pod's are occasionally not starting within the 30s default timeout.
N/A
N/A
N/A
N/A
Should be bc.
Tested on big-02. To confirm the http_timeout setting, I set to 1s and notebooks failed to start and the timeout was displayed in the error message.
N/A
=> Increase JupyterHub Spawner http_timeout

linting_java_checkstyle.xml
N/A
Makes checkstyle actually fail for style complaints rather than just warn.
N/A
N/A
N/A
N/A
N/A
Worked locally to fail checkstyle task when I introduced a style issue.
N/A
=> Upgrade checkstyle warnings to errors, and info to warnings

ansible/playbooks/files/grafana/dashboards/cnpg-dashboard.json
- `maintenance_work_mem` was showing 2MB when set to 2GB. Fixed the dashboard PromQL query to multiply by 1024, like the query for `work_mem` is doing.
N/A
N/A
N/A
N/A
Yes
Tested on `big-02`. Confirmed `maintenance_work_mem` was being correctly set in PG by logging into psql on the cluster and verified the setting.
N/A
=> Fix CNPG dashboard maintenance_work_mem query

models/README.md, models/ollama/middleware.yaml, models/ollama/pv.yaml, models/ollama/values.yaml, models/open-webui/values.yaml
Add `models/README.md` with instructions for deploying Open WebUI, Ollama, and an MCP server that allows LLMs to query our data in Delta Lake via Trino.
Also add files to support these deploys, such as helm values files and a few k8s objects to create.
This is all experimental and POC, so it is quite manual at this time. It is not integrated into the ansible playbooks or even helm charts. Once we get further along the path of deploying these as a proper part of Scout's ansible infrastructure, I'll remove these manual instructions.
None
Performance is currently extremely bad with models running on CPU.
N/A
N/A
None
None
=> Add instructions for POC Open WebUI + Ollama deploy

.github/ci_resources/inventory.yaml, ansible/inventory.example.yaml, ansible/playbooks/services/grafana.yaml, ansible/playbooks/templates/grafana/grafana.values.yaml.j2, ansible/playbooks/templates/loki.values.yaml.j2, ansible/playbooks/vars/monitor_storage.yaml
I had deployed Scout to my tagdev multinode cluster. A spot check of services revealed grafana wasn't up. Investigating that revealed that the pods had not started because the PVCs were not bound to any PVs.
I found that when migrating the lists of `storage_definitions` in the ansible playbooks I had missed the entries for grafana and loki.
This adds those back.
Restore grafana to Scout
- Add back grafana and loki storage definitions to ansible config; they had been inadvertently removed in #139
- Move loki helm values file from `helm` into `ansible` as a template so we can use variables
N/A
Manually deployed Scout to tagdev cluster `{control,big}-03`. Verified grafana started.
N/A
=> Fix grafana broken in #139

.github/ci_resources/inventory.yaml, ansible/inventory.example.yaml, ansible/playbooks/vars/jupyter.values.yaml, helm/jupyter/notebook/requirements.txt
Jupyter AI users can configure a connection to models on an ollama
- Add a dependency on `langchain-ollama` to jupyter's `requirements.txt`. This enables support for configuring connections to models on ollama servers in the jupyter AI plugin.
- Add egress from jupyter to the ollama namespace
This doesn't have a lot of impact now, since I haven't added the ollama deploy to ansible. But this is a small first step that makes development and testing easier (i.e. I won't have to build and deploy a custom jupyter image).
I have previously built the image this way and manually applied it to my dev cluster. I had trouble doing the same more recently with the `containerd` runtime, so I haven't tried it recently. But I'm pretty sure it will still work.
N/A
=> Add jupyter ai ollama lib + egress to jupyter notebook

ansible/inventory.example.yaml, ansible/playbooks/vars/jupyter.values.yaml
Request a GPU for Jupyter notebook pods.
This isn't parameterized, and there is no user control. All Jupyter pod launches will request a single GPU.
I've deployed this on the `03` cluster and was able to use a GPU from a notebook. I believe Charlie did the same on `01`.
This will need to be reconsidered for production, but is fine for our limited demo use case.
The biggest downside is that we'll run out of GPUs very quickly, so only a single user will be able to launch a notebook.
=> Add Jupyter GPU request

ansible/playbooks/services/superset.yaml, helm/superset/Dockerfile
- Fix Superset login issue preventing user login
- The superset login page was infinitely redirecting back to itself and restarting the login process preventing user login.
- No longer need to update the Superset Dockerfile, our current image has the needed python libraries.
Does not fix superset authZ role mapping issues. All users are still admin.
N/A
N/A
N/A
N/A
Tested manually on a fresh install of Scout on big-02
Helpful links:
[Keycloak-Specific Configuration using Flask-OIDC](https://superset.apache.org/docs/configuration/configuring-superset/#keycloak-specific-configuration-using-flask-oidc)
[How to log out of SSO with Cognito #10712](https://github.com/apache/superset/discussions/10712)
[Integrating Keycloak with Superset (v4.1.1) - Issue with OAuth …
=> Fix Superset Infinite Login Redirect

ansible/playbooks/services/keycloak.yaml, ansible/playbooks/templates/keycloak/scout-realm.json.j2
- Keycloak user and admin events (such as user registration, group membership changes, and login events) are now available in Grafana for monitoring and auditing
- Enables jboss-logging feature in Keycloak to log admin and user events to the syslog. Loki then makes the logs available in Grafana for easy searching.
- Bump jboss event logging level to info instead of the default debug level to reduce log noise
N/A
Improves security monitoring with complete logs of user authentication events
N/A
Event logs container user identifiers and timestamps.
Should be. This change only adds logging configuration.
Tested on big-02. Confirmed Keycloak event logs were available in Loki
N/A
=> Add Keycloak audit logging for user and admin events

.github/ci_resources/inventory.yaml, ansible/inventory.example.yaml, ansible/playbooks/k3s.yaml, ansible/playbooks/lake.yaml, ansible/playbooks/services/minio.yaml, ansible/playbooks/tasks/storage_dir_create.yaml, ansible/playbooks/tasks/storage_setup.yaml, ansible/playbooks/vars/lake_storage.yaml, ansible/playbooks/vars/minio.yaml, models/README.md, models/open-webui/values.yaml
Minio will be more resilient when run in a multinode cluster.
Minio can now be configured with multiple replica pods spread across the nodes in a multinode cluster, and to use multiple volume mounts per node (single- or multinode).
Two main points of configuration:
- Added a new group in ansible called `minio_hosts`. Any hosts added here (say through groups like `server` or `workers`) will have minio deployed on them.
- Added a configuration variable `minio_volumes_per_server`. If multiple minio pods are to be deployed this must be set > 1. Even if a single minio is deployed this can optionally be set > 1.
The directories that get created on each node are named `{{ minio_dir }}{{ i }}` for all `i` in the range `0` to `minio_volumes_per_server-1`, so if you want the minio volumes to use …
=> Enable configuration to spread minio across nodes

ansible/playbooks/services/superset.yaml
Bitnami has removed their docker images to support a paywall strategy. But they have copied the existing images to a "legacy" account. See https://github.com/bitnami/charts/issues/35164
Superset depends on bitnami charts / images. See https://github.com/apache/superset/issues/34414
We can _temporarily_ work around this by pointing the superset redis chart to the legacy bitnami image. But longer term hopefully superset will update their chart to remove the bitnami dependency; we will need to update our superset chart at that time.
This restores existing functionality. As far as I know there are no functional differences between the old image we used to use for this and the legacy image we use now.
Successfully deployed this change to the `03` cluster.
N/A
=> Use bitnamilegacy image for superset redis chart

ansible/playbooks/helm.yaml, ansible/playbooks/main.yaml
Once I merged #171, the [CI job](https://github.com/washu-tag/scout/actions/runs/18018994633) failed on main. I'm not sure why, because the same exact thing succeeded when [it was run on the PR](https://github.com/washu-tag/scout/actions/runs/17987831795).
It seems that some of my ansible changes have string defaults when they should have booleans. This changes that.
This enables the proper default behavior when the `install_helm` and `clone_scout_repo` inventory variables are unset.
I ran the CI, which passed. https://github.com/washu-tag/scout/actions/runs/17987831795
This doesn't inspire much confidence, though, since the code with the bug already ran through CI and it passed, so... 🤷🏼 .
N/A
=> Fix string defaults in boolean condition

ansible/playbooks/services/superset.yaml
- Fix query timeout issues in Superset that leave Scout dashboards stuck with spinners.
- Updated SQLALCHEMY_ENGINE_OPTIONS in Superset config
References:
- [SO thread](https://stackoverflow.com/questions/67839302/superset-dashboard-failed-with-timeouterror-queuepool-limit-of-size-5-overflow)
- [Superset issue #30286](https://github.com/apache/superset/issues/30286)
- [Superset issue #8207](https://github.com/apache/superset/issues/8207)
N/A
N/A
Allows for more concurrent connections, query execution speed not expected to improve.
N/A
Yes
I looked at the Grafana stats for CPU and Mem usage during Dan's usage, it seemed safe to increase the pool size. Tested on `big02` and patched `tag-big-01` with no issues during Dan's demo.
Verified before and after values using:
```sh
$ k exec -n …
```
=> Increase SQLAlchemy pool size for Superset
